default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: byzgaev
  password:

development:
  <<: *default
  database: mailchat_development

test: &test
  <<: *default
  database: mailchat_test

production:
  <<: *default
  database: mailchat_production

cucumber:
  <<: *test